Task_1_2_2
animovscw/OOP pull request #7
Opened 2024-10-24 03:25 UTC by animovscw

2024-10-24 15:26 UTC, galinabykova requested changes
мягкий засчитан, но не затягивай с правками и ответами на вопросы

2024-10-24 15:26 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/anisimov/HashTable.java
> +                iterator.remove();
это теоретический вопрос, на него надо обязательно ответить, а не просто исправить
у тебя тут remove, но при этом ты нигде его не переопределяешь. Где определена эта реализация remove и что она делает?

2024-10-24 15:26 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/anisimov/HashTable.java
> +        return new Iterator<>() {
объект какого класса ты тут создаёшь?

2024-10-24 15:26 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/anisimov/HashTable.java
> +            return null;
почему ты решил возвращать null, а не бросать исключение?

2024-10-24 15:26 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/anisimov/HashTable.java
> +        StringBuilder sb = new StringBuilder();
почему ты используешь тут StringBuilder, а не String?

2024-10-24 15:26 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/anisimov/HashTable.java
> +        K key;
тут наверно можно сделать private, у тебя  есть геттеры-сеттеры

2024-10-24 15:26 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/anisimov/HashTable.java
> +        table = new LinkedList[oldTable.length * 2];
тут можно тип  LinkedList указать или wildcard

2024-10-24 15:26 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/anisimov/HashTable.java
> +                        if (Objects.equals(entry.getKey(), otherEntry.getKey())) {
не поняла это условие, поясни как у тебя этот метод устроен

2024-10-24 15:26 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/anisimov/HashTable.java
> +    private int modCount;
опиши, для чего нужна эта переменная

2024-10-24 15:26 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/anisimov/HashTable.java
> +    private LinkedList<Entry<K, V>>[] table;
мне кажется, нет особого смысла хранить Entry в списке, у всех элементов одного списка вроде бы один ключ

2024-10-31 02:39 UTC, animovscw commented on Task_1_2_2/src/main/java/ru/nsu/anisimov/HashTable.java
> +                iterator.remove();
Здесь remove() является встроенной операцией Iterator, то есть он, по идее, объявлен и описан в Iterator, что дает возможность реализовывать этот метод каждой коллекции ( в данном случае LinkedList). 
Метод удаляет текущий элемент из LinkedList в массиве table, сам он вызывается в методе HashTable.remove(K key).

2024-10-31 02:43 UTC, animovscw commented on Task_1_2_2/src/main/java/ru/nsu/anisimov/HashTable.java
> +                iterator.remove();
Когда я изучал как реализовать эту задачу, был пример такого использования. Такой подход интересен тем, что то, что используется в Iterator, не зависит от конкретного типа коллекции, и значит его можно использовать для каждого его типа.
Насколько я понял ваш комментарий, этот метод неправильно у меня реализован, то есть я должен был объявить его самостоятельно?

2024-10-31 03:01 UTC, animovscw commented on Task_1_2_2/src/main/java/ru/nsu/anisimov/HashTable.java
> +        return new Iterator<>() {
Здесь создается анонимный класс, то есть класс, который не имеет имени. Он реализует Iterator<..>, но не требует определения нового имени класса. 
Задумывалось, что он дает возможность реализовать Iterator только для текущего экземпляра.

2024-10-31 03:04 UTC, animovscw commented on Task_1_2_2/src/main/java/ru/nsu/anisimov/HashTable.java
> +            return null;
Возвращение null упрощает проверку отсутствия ключа без необходимости перехватывать исключения. Проблемой возвращения null является то, что он может быть либо значением, либо указателем на отсутствие ключа.

2024-10-31 03:12 UTC, animovscw commented on Task_1_2_2/src/main/java/ru/nsu/anisimov/HashTable.java
> +        StringBuilder sb = new StringBuilder();
Из-за меньшего использования памяти и "повышения" производительности.
В String каждый раз используя += происходит создание нового объекта String, который затем копирует все предыдущие символы, добавляя новые. Это долго и неэффективно.
Я использовал один объект StringBuilder, который накапливает данные в своем внутреннем буфере, не создавая новых объектов при каждой итерации. 
По крайней мере, задумывалась реализация с именно такой логикой.

2024-10-31 03:32 UTC, animovscw commented on Task_1_2_2/src/main/java/ru/nsu/anisimov/HashTable.java
> +                        if (Objects.equals(entry.getKey(), otherEntry.getKey())) {
Здесь выполняется поиск элемента с тем же ключом в другой хеш-таблице that. Мы проверяем, есть ли в that элемент с ключом, равным ключу entry, если мы такой нашли, то делаем проверку эквивалентны ли они.
Цикл перебирает все связные списки (bucket), которые хранятс в that.table = LinkedList. ```<? extends Entry<?, ?>>``` означает, что принимаются любые списки, содержащие объекты, наследующие Entry с любыми типами ключей и значений.
Проверка на null, что значит пустой ли bucket, необходима для избежания ошибок NullPointerException.
Если не пустой, то перебираются все элементы Entry.

2024-10-31 03:35 UTC, animovscw commented on Task_1_2_2/src/main/java/ru/nsu/anisimov/HashTable.java
> +                        if (Objects.equals(entry.getKey(), otherEntry.getKey())) {
```if (Objects.equals(entry.getKey(), otherEntry.getKey())) {``` проверяет, равен ли ключ текущего элемента entry

2024-10-31 06:07 UTC, animovscw commented on Task_1_2_2/src/main/java/ru/nsu/anisimov/HashTable.java
> +    private int modCount;
Переменная нужна для отслеживания модификаций коллекции: добавление, удаление или изменение. Также она нужна для обнаружения ConcurrentModificationException: 

- при создании итератора expectedModCount = modCount;
- перед каждым вызовом next() или hasNext() проверка равны ли expectedModCount и modCount;
- если modCount изменился, то выбрасывается ```ConcurrentModificationException```

2024-10-31 06:26 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/anisimov/HashTable.java
> +                iterator.remove();
ты прав, это действительно реализация по умолчанию интерфейса remove, но у неё достаточно специфичное поведение
https://docs.oracle.com/javase/8/docs/api/java/util/Iterator.html#remove--
она просто выбрасывает исключение)
если хочешь использовать этот метод, нужно его переопределить)

2024-10-31 06:34 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/anisimov/HashTable.java
> +    private LinkedList<Entry<K, V>>[] table;
а, это неправда, у меня хэшкод с ключом в голове перемешался)

2024-11-05 03:47 UTC, galinabykova approved these changes
Мне кажется, лучше в этой лабе было использовать ArrayList вместо массива. У тебя в некоторым местах из-за использования массива не указан тип и из-за этого не везде осуществляются проверки типов, мне кажется, это не очень хорошо.

Также в следующий раз, пожалуйста, не затягивай с правками. Лучше присылать первую скорректированную версию хотя бы за два дня до дедлайна.  В следующий раз, если у меня будут замечания, а твоя первая версия будет отправлена в вечер дедлайна, не засчитаю

2024-11-05 03:47 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/anisimov/HashTable.java
> +    public boolean equals(Object o) {
у тебя переопределён equals,  но не определён hashcode, может быть ситуация, когда объекты равны, а их хэш-коды нет, это нарушение контракта

2024-11-05 03:47 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/anisimov/HashTable.java
> +        table = new LinkedList[oldTable.length * 2];
я имела ввиду другую строчку, но там, наверно, не получилось бы

2024-11-08 03:08 UTC, merged