Task_1_3_1
animovscw/OOP pull request #8
Opened 2024-11-10 15:14 UTC by animovscw

2024-11-11 05:52 UTC, galinabykova requested changes
мягкий засчитан

2024-11-11 05:52 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/anisimov/SubstringSearch.java
> +        ArrayList<Integer> indexes = new ArrayList<>();
здесь, наверно, нужен Long, так как может быть индекс большого размера

2024-11-11 05:52 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/anisimov/SubstringSearch.java
> +            String current = new String(buffer);
может тут лучше StringBuilder, а то ты модифицируешь строку

2024-11-11 05:52 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/anisimov/SubstringSearchTest.java
добавь тест, в котором подстрока содержит свой префикс (например, ааааааааа и файл аааааааааааааааааа)
также нужен большой файл, не помещающийся в оперативную память твоего компьютера (его надо генерировать прямо в тесте, потому что на гитхаб ты его не зальёшь и читать как файл, а не ресурс)

2024-11-11 05:52 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/anisimov/SubstringSearch.java
> +    public static ArrayList<Integer> resourceSearch(String resourcename, String subname) throws IOException {
предлагаю ещё обернуть исключение в новое (Exception wrapping) для уточнения контекста

2024-11-15 04:58 UTC, animovscw commented
Я хотел использовать ```e.printStackTrace()```, но рекомендуется не использовать его, поэтому я пока что закомментировал эту строчку. Я не совсем понял, что значит robust logic facility?
```
Such statements are often used for temporary debugging and should be either removed from the production code or replaced with a more robust logging facility
```

2024-11-15 04:59 UTC, animovscw commented
> Я хотел использовать `e.printStackTrace()`, но рекомендуется не использовать его, поэтому я пока что закомментировал эту строчку. Я не совсем понял, что значит robust logic facility?
> 
> ```
> Such statements are often used for temporary debugging and should be either removed from the production code or replaced with a more robust logging facility
> ```

2024-11-15 05:29 UTC, galinabykova commented
> @galinabykova, я хотел использовать `e.printStackTrace()`, но рекомендуется не использовать его, поэтому я пока что закомментировал эту строчку. Я не совсем понял, что значит robust logic facility?
> 
> ```
> Such statements are often used for temporary debugging and should be either removed from the production code or replaced with a more robust logging facility
> ```

 я думаю, тут имеются ввиду библиотеки для логгирования. Логгировние это как раз сохранение какой-либо информации о ходе работы программы. При возникновении ошибок, которые не получается воспоизвести, из логов программисты могут понять, что произошло. И тебе тут говорят использовать другие средства для логгирования (для логгирования есть специальные библиотеки), а не  printStakeTrace, удобный для отладки

2024-11-17 13:59 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/anisimov/SubstringSearchTest.java
@animovscw не увидела тест с пересечениями (в котором подстрока содержит свой префикс, например, ааааааааа и файл аааааааааааааааааа)

2024-11-17 14:01 UTC, galinabykova requested changes

2024-11-17 14:01 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/anisimov/SubstringSearch.java
> +            throw new RuntimeException("Fail to read the resource: " + resourceName, e);
RuntimeException обычно используют для ситуаций, которые возникают по вине программиста. У тебя другая ситуация - лучше создать свой класс исключений

2024-11-17 14:01 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/anisimov/SubstringSearch.java
> +            throw new RuntimeException("Fail to read the resource: " + resourceName, e);
наследник Exception

2024-11-17 15:17 UTC, galinabykova approved these changes

2024-11-17 15:30 UTC, merged